# StyLua configuration for markdown-plus.nvim
# https://github.com/JohnnyMorganz/StyLua

# Use Lua 5.1 (LuaJIT) for Neovim
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"

[sort_requires]
enabled = false
