vim.wo.list = true
vim.wo.listchars = "tab:» ,lead:•,trail:⌟"
vim.wo.wrap = true
vim.wo.linebreak = true
vim.wo.number = false
vim.wo.conceallevel = 2
vim.wo.scrolloff = 5
vim.wo.spell = true
vim.bo.spelllang = "en,it"
vim.bo.spellfile = vim.fn.stdpath("config") .. "/spell/exceptions.utf-8.add"
